import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles.css'
import './audit-hardening.css'
import './precision-opening.css'
import './sylva-kinetic.css'
import './production-assets.css'
import './final-polish.css'
import './family-details.css'
import './logo-branding.css'
import './designer-credit.css'
import './typography.css'
import './design-system/opening-side.css'
import './design-system/language-selection.css'
import './design-system/forest-cinematic.css'
import './design-system/tiger-reveal.css'
import './design-system/tiger-crest-transition.css'
import './cinematicEnhancements.js'
import './sylvaKinetic.js'
import './rsvpScrollGuard.js'
import './familyDetails.js'
import './logoBranding.js'
import './designerCredit.js'
import './design-system/openingSide.js'
import './design-system/languageSelection.js'
import './design-system/forestCinematic.js'
import './design-system/tigerReveal.js'
import './design-system/tigerCrestTransition.js'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
