import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles.css'
import './audit-hardening.css'
import './precision-opening.css'
import './sylva-kinetic.css'
import './production-assets.css'
import './final-polish.css'
import './family-details.css'
import './logo-branding.css'
import './designer-credit.css'
import './typography.css'
import './design-system/opening-side.css'
import './design-system/language-selection.css'
import './design-system/forest-cinematic.css'
import './design-system/tiger-reveal.css'
import './design-system/tiger-crest-transition.css'
import './design-system/physical-passport.css'
import './design-system/couple-editorial-hero.css'
import './design-system/family-introduction.css'
import './design-system/couple-story.css'
import './design-system/corbett-destination.css'
import './design-system/itinerary-navigator.css'
import './design-system/celebration-chapters.css'
import './design-system/event-photography.css'
import './design-system/written-in-stars.css'
import './design-system/wyndham-venue.css'
import './design-system/glass-architecture.css'
import './design-system/stay-travel-transport.css'
import './design-system/transport-details-modal.css'
import './design-system/wedding-gallery.css'
import './design-system/bottom-navigation.css'
import './design-system/rsvp-experience.css'
import './design-system/rsvp-confirmation.css'
import './design-system/closing-wedding-screen.css'
import './design-system/opening-corrections.css'
import './design-system/opening-stability.css'
import './design-system/global-motion.css'
import './design-system/opening-hit-target-stability.css'
import './cinematicEnhancements.js'
import './sylvaKinetic.js'
import './rsvpScrollGuard.js'
import './familyDetails.js'
import './logoBranding.js'
import './designerCredit.js'
import './design-system/openingSide.js'
import './design-system/languageSelection.js'
import './design-system/forestCinematic.js'
import './design-system/tigerReveal.js'
import './design-system/tigerCrestTransition.js'
import './design-system/physicalPassport.js'
import './design-system/coupleEditorialHero.js'
import './design-system/familyIntroduction.js'
import './design-system/coupleStory.js'
import './design-system/corbettDestination.js'
import './design-system/itineraryNavigator.js'
import './design-system/celebrationChapters.js'
import './design-system/eventPhotography.js'
import './design-system/writtenInStars.js'
import './design-system/wyndhamVenue.js'
import './design-system/glassArchitecture.js'
import './design-system/stayTravelTransport.js'
import './design-system/transport-details-modal.js'
import './design-system/weddingGallery.js'
import './design-system/bottomNavigation.js'
import './design-system/rsvp-experience.js'
import './design-system/rsvpConfirmation.js'
import './design-system/closing-wedding-screen.js'
import './design-system/openingCorrections.js'
import './design-system/globalMotion.js'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
